[versions]
agp = "8.6.1"
commonsCollections4 = "4.3"
constraintlayout = "2.1.4"
converterGson = "2.9.0"
coreKtx = "1.13.1"
eventbus = "3.2.0"
glide = "4.12.0"
hmspickerview = "0.2.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
kotlinStdlibJdk7 = "1.6.21"
legacyPreferenceV14 = "1.0.0"
lifecycleExtensions = "2.2.0"
material = "1.12.0"
okhttp3Integration = "4.12.0"
preferenceKtx = "1.2.1"
recyclerview = "1.3.2"
recyclerviewSelection = "1.1.0"
roomRuntime = "2.6.1"
kotlin = "2.0.20"
lifecycleViewmodelKtxVersion = "2.8.6"
work_version = "2.9.1"
compressor_version="1.6.0"

[libraries]
commons-collections4 = { module = "org.apache.commons:commons-collections4", version.ref = "commonsCollections4" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
eventbus = { module = "org.greenrobot:eventbus", version.ref = "eventbus" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
hmspickerview = { module = "xyz.aprildown:HmsPickerView", version.ref = "hmspickerview" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlin-stdlib-jdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlinStdlibJdk7" }
legacy-preference-v14 = { module = "androidx.legacy:legacy-preference-v14", version.ref = "legacyPreferenceV14" }
lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycleExtensions" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
okhttp3-integration = { module = "com.github.bumptech.glide:okhttp3-integration", version.ref = "okhttp3Integration" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
recyclerview-selection = { module = "androidx.recyclerview:recyclerview-selection", version.ref = "recyclerviewSelection" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtxVersion" }
workmanager-ktx = { group = "androidx.work", name="work-runtime-ktx", version.ref = "work_version" }
compressor = { group="com.github.Shouheng88", name="compressor", version.ref = "compressor_version"}


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }